#!/usr/bin/env python3
from pathlib import Path

ROOT = Path.cwd()

files = {
    "components/MatchCard.tsx": 'import { formatMatchDate, formatSpainTimeFromEt, resultLabel } from "@/lib/format";\nimport { getMatchPredictions, signFromResult } from "@/lib/scoring";\nimport type { Match, MatchResult, Pick } from "@/lib/types";\n\nexport function MatchCard({\n  match,\n  result,\n}: {\n  match: Match;\n  result?: MatchResult;\n}) {\n  const actual = signFromResult(result);\n  const predictions = getMatchPredictions(match.id);\n\n  const grouped = predictions.reduce(\n    (acc, item) => {\n      acc[item.pick].push(item.player);\n      return acc;\n    },\n    { "1": [], X: [], "2": [] } as Record<Pick, string[]>\n  );\n\n  const renderPick = (pick: Pick) => {\n    const names = grouped[pick];\n\n    return (\n      <details className="pick-details">\n        <summary className={actual === pick ? "chip hit pick-summary" : "chip pick-summary"}>\n          {pick} · {names.length}\n        </summary>\n        <div className="pick-tooltip">\n          <div className="pick-tooltip-title">Han puesto {pick}</div>\n          <div>{names.join(", ")}</div>\n        </div>\n      </details>\n    );\n  };\n\n  return (\n    <article className="match-card">\n      <div className="match-top">\n        <div>\n          <div className="meta-row">\n            <span>{formatMatchDate(match.date)}</span>\n            <span className="group-chip">Grupo {match.group ?? "—"}</span>\n          </div>\n          <div className="match-label">{match.home} - {match.away}</div>\n          <div className="muted match-time-row">\n            {match.city ? <span>{match.city}</span> : null}\n            {match.timeLocal ? <span>{match.timeLocal} local</span> : null}\n            {match.timeEt ? <span>{formatSpainTimeFromEt(match.timeEt)}</span> : null}\n          </div>\n        </div>\n        <div className={result ? "score done" : "score"}>{resultLabel(result)}</div>\n      </div>\n\n      <div className="pick-row">\n        {renderPick("1")}\n        {renderPick("X")}\n        {renderPick("2")}\n      </div>\n    </article>\n  );\n}\n',
    "lib/format.ts": 'import type { MatchResult, Pick } from "./types";\n\nexport function pickLabel(pick?: Pick): string {\n  if (!pick) return "—";\n  if (pick === "1") return "1";\n  if (pick === "2") return "2";\n  return "X";\n}\n\nexport function resultLabel(result?: MatchResult): string {\n  if (!result) return "Pendiente";\n  return `${result.homeGoals}-${result.awayGoals}`;\n}\n\nexport function normalizePlayerForUrl(player: string): string {\n  return encodeURIComponent(player);\n}\n\nexport function formatMatchDate(date?: string): string {\n  if (!date) return "Fecha pendiente";\n\n  const parsed = new Date(`${date}T12:00:00`);\n  return new Intl.DateTimeFormat("es-ES", {\n    weekday: "short",\n    day: "numeric",\n    month: "short",\n  }).format(parsed);\n}\n\nexport function formatLongMatchDate(date?: string): string {\n  if (!date) return "Fecha pendiente";\n\n  const parsed = new Date(`${date}T12:00:00`);\n  return new Intl.DateTimeFormat("es-ES", {\n    weekday: "long",\n    day: "numeric",\n    month: "long",\n  }).format(parsed);\n}\n\nexport function formatSpainTimeFromEt(timeEt?: string): string {\n  if (!timeEt) return "";\n\n  const [rawHour, rawMinute = "00"] = timeEt.split(":");\n  const hour = Number(rawHour);\n  const minute = Number(rawMinute);\n\n  if (!Number.isFinite(hour) || !Number.isFinite(minute)) {\n    return `${timeEt} España`;\n  }\n\n  // En junio/julio, la costa Este está en EDT (UTC-4) y España peninsular en CEST (UTC+2).\n  // Por tanto, hora española = ET + 6 horas.\n  const totalHours = hour + 6;\n  const spainHour = totalHours % 24;\n  const nextDay = totalHours >= 24;\n\n  const formattedHour = String(spainHour).padStart(2, "0");\n  const formattedMinute = String(minute).padStart(2, "0");\n\n  return `${formattedHour}:${formattedMinute} España${nextDay ? " (+1)" : ""}`;\n}\n',
    "app/pronosticos/page.tsx": 'import Link from "next/link";\nimport { normalizePlayerForUrl } from "@/lib/format";\nimport { getPlayerSummaries } from "@/lib/scoring";\n\nexport default function PredictionsPage() {\n  const players = getPlayerSummaries();\n\n  return (\n    <section>\n      <div className="page-header">\n        <h1>Pronósticos</h1>\n        <p>La quiniela individual de cada jugador.</p>\n      </div>\n\n      <div className="grid-list">\n        {players.map((row) => (\n          <Link key={row.player} href={`/pronosticos/${normalizePlayerForUrl(row.player)}`} className="player-tile">\n            <span>{row.player}</span>\n            <div className="pronostic-summary">\n              {row.played === 0 ? (\n                <>Ver quiniela</>\n              ) : (\n                <>{row.correct} aciertos · {row.wrong} fallos</>\n              )}\n            </div>\n          </Link>\n        ))}\n      </div>\n    </section>\n  );\n}\n',
    "app/pronosticos/[player]/page.tsx": 'import Link from "next/link";\nimport { notFound } from "next/navigation";\nimport { formatMatchDate, resultLabel } from "@/lib/format";\nimport { getPlayerPredictions, getPlayerSummary, getPlayers, getResults } from "@/lib/scoring";\n\nexport function generateStaticParams() {\n  return getPlayers().map((player) => ({ player }));\n}\n\nexport default async function PlayerPredictionPage({\n  params,\n}: {\n  params: Promise<{ player: string }>;\n}) {\n  const { player: rawPlayer } = await params;\n  const player = decodeURIComponent(rawPlayer);\n\n  const predictions = getPlayerPredictions(player);\n  if (predictions.length === 0) notFound();\n\n  const summary = getPlayerSummary(player);\n  const results = getResults();\n\n  return (\n    <section>\n      <div className="page-header">\n        <Link href="/pronosticos" className="back">← Pronósticos</Link>\n        <h1>{player}</h1>\n        <p>\n          {summary.played === 0\n            ? "Quiniela completa"\n            : `${summary.correct} aciertos · ${summary.wrong} fallos · ${summary.pending} pendientes`}\n        </p>\n      </div>\n\n      <div className="stack">\n        {predictions.map((item) => (\n          <article key={item.matchId} className="prediction-card">\n            <div>\n              <div className="meta-row">\n                <span>{formatMatchDate(item.match.date)}</span>\n                <span className="group-chip">Grupo {item.match.group ?? "—"}</span>\n              </div>\n              <div className="match-label">{item.match.label}</div>\n              <div className="muted">Resultado: {resultLabel(results[item.matchId])}</div>\n            </div>\n            <div className="prediction-right">\n              <span className="chip">{item.pick}</span>\n              {item.isCorrect === null ? (\n                <span className="pill pending">Pendiente</span>\n              ) : item.isCorrect ? (\n                <span className="pill ok">+1</span>\n              ) : (\n                <span className="pill ko">0</span>\n              )}\n            </div>\n          </article>\n        ))}\n      </div>\n    </section>\n  );\n}\n',
}

for rel, content in files.items():
    path = ROOT / rel
    if not path.exists():
        raise FileNotFoundError(f"No encuentro {rel}. Ejecuta este script desde la raíz del proyecto mundial-porra-2026.")
    path.write_text(content, encoding="utf-8")

css_path = ROOT / "app/globals.css"
if not css_path.exists():
    raise FileNotFoundError("No encuentro app/globals.css. Ejecuta este script desde la raíz del proyecto.")

css = css_path.read_text(encoding="utf-8")
marker = "/* V2.1: hora española y desplegable de pronósticos por partido */"
if marker not in css:
    css_path.write_text(css.rstrip() + "\n\n" + '/* V2.1: hora española y desplegable de pronósticos por partido */\n.match-time-row {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 6px;\n  align-items: center;\n}\n\n.match-time-row span + span::before {\n  content: "·";\n  margin-right: 6px;\n  color: var(--muted);\n}\n\n.pick-details {\n  position: relative;\n}\n\n.pick-summary {\n  cursor: pointer;\n  list-style: none;\n  user-select: none;\n}\n\n.pick-summary::-webkit-details-marker {\n  display: none;\n}\n\n.pick-tooltip {\n  display: none;\n  position: absolute;\n  left: 0;\n  top: calc(100% + 8px);\n  z-index: 20;\n  width: min(260px, calc(100vw - 42px));\n  padding: 10px 12px;\n  border: 1px solid var(--line);\n  border-radius: 14px;\n  background: var(--card, var(--panel, #fff));\n  color: var(--text);\n  box-shadow: 0 14px 34px rgba(35, 57, 80, 0.18);\n  font-size: 13px;\n  line-height: 1.35;\n}\n\n.pick-details[open] .pick-tooltip {\n  display: block;\n}\n\n.pick-tooltip-title {\n  margin-bottom: 4px;\n  color: var(--muted);\n  font-size: 12px;\n  font-weight: 800;\n}\n\n.pick-row .pick-details:last-child .pick-tooltip {\n  left: auto;\n  right: 0;\n}\n', encoding="utf-8")

print("Aplicada versión 2.1: hora española, Pronósticos más limpio y desplegable de nombres en Partidos.")
